# Generated by Django 5.2.17 on 2026-09-28 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(default='', max_length=160)),
                ('date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=10)),
                ('category', models.CharField(default='Activity', max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('recommended_time', models.CharField(blank=True, default='', max_length=60)),
                ('estimated_cost', models.FloatField(default=0)),
                ('duration', models.CharField(blank=True, default='', max_length=60)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.itineraryday')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(db_index=True, max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=3)),
                ('travelers', models.PositiveIntegerField(default=2)),
                ('budget', models.FloatField(default=30000)),
                ('travel_style', models.CharField(default='Balanced', max_length=40)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('food_preferences', models.CharField(blank=True, default='', max_length=200)),
                ('accommodation', models.CharField(blank=True, default='', max_length=60)),
                ('transportation', models.CharField(blank=True, default='', max_length=60)),
                ('summary', models.TextField(blank=True, default='')),
                ('estimated_total_cost', models.FloatField(default=0)),
                ('share_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', '-created_at'], name='trips_trip_user_id_2f4a85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together={('trip', 'day_number')},
        ),
    ]
