# Generated by Django 5.2.17 on 2026-09-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trip',
            name='trips_trip_user_id_2f4a85_idx',
        ),
        migrations.RemoveField(
            model_name='itineraryday',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='trip',
            name='adults',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='trip',
            name='budget_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trip',
            name='budget_tier',
            field=models.CharField(default='Moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='trip',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='travel_styles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='traveler_type',
            field=models.CharField(default='Couple', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='weather_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='weather_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.FloatField(default=25000),
        ),
        migrations.AlterField(
            model_name='trip',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
